export const UI = {
  SIDEBAR_TOGGLE : "UI_SIDEBAR_TOGGLE",
  REDIRECT: "UI_REDIRECT",
  CHANGE_PATH: "CHANGE_PATH",
  ALL_ORDERS: "ALL_ORDERS"
}

export const Auth = {
  LOGIN: "USR_LOGIN",
  LOGIN_REJECT: "USR_LOGIN_REJECTED",
  LOGIN_FULFILLED: "USR_LOGIN_FULFILLED",
  LOGOUT: "USR_LOGOUT",

  CHECK_AUTH: "USR_CHECK_AUTH",
  CHECK_AUTH_REJECT: "USR_CHECK_AUTH_REJECTED",
  CHECK_AUTH_FULFILLED: "USR_CHECK_AUTH_FULFILLED",
}

export const Item = {
  GET_ALL_ITEMS: "ITM_GET_ALL",
  GET_ALL_ITEMS_REJECT: "ITM_GET_ALL_REJECTED",
  GET_ALL_ITEMS_FULFILLED: "ITM_GET_ALL_FULFILLED",

  CREATE_ITEM: "ITM_CREATE_ITEM",
  CREATE_ITEM_REJECT: "ITM_CREATE_ITEM_REJECTED",
  CREATE_ITEM_FULFILLED: "ITM_CREATE_ITEM_FULFILLED",
}

export const Order = {
  GET_ALL_ORDERS: "ODR_GET_ALL",
  GET_ALL_ORDERS_REJECT: "ODR_GET_ALL_REJECTED",
  GET_ALL_ORDERS_FULFILLED: "ODR_GET_ALL_FULFILLED",

  ADD_ITEM_TO_ORDER:            "ODR_ADD_ITEM_TO_ORDER",
  ADD_ITEM_TO_ORDER_REJECT:     "ODR_ADD_ITEM_TO_ORDER_REJECTED",
  ADD_ITEM_TO_ORDER_FULFILLED:  "ODR_ADD_ITEM_TO_ORDER_FULFILLED",

  CREATE_ORDER:           'ODR_CREATE_ORDER',
  CREATE_ORDER_REJECT:    'ODR_CREATE_ORDER_REJECTED',
  CREATE_ORDER_FULFILLED: 'ODR_CREATE_ORDER_FULFILLED',

  DELETE_ITEM_FROM_ORDER:           'ODR_DELETE_ITEM_FROM_ORDER',
  DELETE_ITEM_FROM_ORDER_REJECT:    'ODR_DELETE_ITEM_FROM_ORDER_REJECTED',
  DELETE_ITEM_FROM_ORDER_FULFILLED: 'ODR_DELETE_ITEM_FROM_ORDER_FULFILLED',

  SET_ORDER_STATUS:           'ODR_SET_ORDER_STATUS',
  SET_ORDER_STATUS_REJECT:    'ODR_SET_ORDER_STATUS_REJECTED',
  SET_ORDER_STATUS_FULFILLED: 'ODR_SET_ORDER_STATUS_FULFILLED',

  SET_CURRENT_ORDER: 'ODR_SET_CURRENT_ORDER'
}