export const UI = {
  SIDEBAR_TOGGLE : "UI_SIDEBAR_TOGGLE",
  REDIRECT: "UI_REDIRECT"
}

export const Auth = {
  LOGIN: "USR_LOGIN",
  LOGIN_REJECT: "USR_LOGIN_REJECTED",
  LOGIN_FULFILLED: "USR_LOGIN_FULFILLED",
}

export const Item = {
  GET_ALL_ITEMS: "ITM_GET_ALL",
  GET_ALL_ITEMS_REJECT: "ITM_GET_ALL_REJECT",
  GET_ALL_ITEMS_FULFILLED: "ITM_GET_ALL_FULFILLED",

  CREATE_ITEM: "ITM_CREATE_ITEM",
  CREATE_ITEM_REJECT: "ITM_CREATE_ITEM_REJECT",
  CREATE_ITEM_FULFILLED: "ITM_CREATE_ITEM_FULFILLED",
}

export const Order = {
  GET_ALL_ORDERS: "ITM_GET_ALL",
  GET_ALL_ORDERS_REJECT: "ITM_GET_ALL_REJECT",
  GET_ALL_ORDERS_FULFILLED: "ITM_GET_ALL_FULFILLED",
}